services:
    sonata.admin.position:
        class: SlashStudio\AppBundle\Admin\PositionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.positions", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Position
            - ~

    sonata.admin.nationality:
        class: SlashStudio\AppBundle\Admin\NationalityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.nationalities", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Nationality
            - ~

    sonata.admin.partnership:
        class: SlashStudio\AppBundle\Admin\PartnershipAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.partnership", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Partnership
            - ~

    sonata.admin.simple_page:
        class: SlashStudio\AppBundle\Admin\SimplePageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.pages.simple", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\SimplePage
            - ~

    sonata.admin.slide:
        class: SlashStudio\AppBundle\Admin\SlideAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.slides", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Slide
            - ~

    sonata.admin.team:
        class: SlashStudio\AppBundle\Admin\TeamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.team.information", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Team
            - ~

    sonata.admin.player:
        class: SlashStudio\AppBundle\Admin\PlayerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.players", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Player
            - ~

    sonata.admin.achievement:
        class: SlashStudio\AppBundle\Admin\AchievementAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.team.achievements", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Achievement
            - ~

    sonata.admin.post:
        class: SlashStudio\AppBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.posts.usual", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Post
            - ~

    sonata.admin.product:
        class: SlashStudio\AppBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.products", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Product
            - ~

    sonata.admin.mediapost:
        class: SlashStudio\AppBundle\Admin\MediaPostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.posts.media", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\MediaPost
            - ~

    sonata.admin.meta:
        class: SlashStudio\AppBundle\Admin\MetaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.meta", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Meta
            - ~

    sonata.admin.cheerleader_team:
        class: SlashStudio\AppBundle\Admin\CheerleaderTeamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.cheerleader.team", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\CheerleaderTeam
            - ~

    sonata.admin.cheerleaders:
        class: SlashStudio\AppBundle\Admin\CheerleaderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_manager: my_model_manager, label: "admin.cheerleader.cheerleaders", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Cheerleader
            - ~
#
#    sonata.admin.users:
#        class: SlashStudio\AppBundle\Admin\UserAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, label: "admin.user.class" }
#        arguments:
#            - ~
#            - Application\Sonata\UserBundle\Entity\User
#            - ~
