services:
    sonata.admin.position:
        class: SlashStudio\AppBundle\Admin\PositionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Positions" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Position
            - ~
#        calls:
#            - [ setTranslationDomain, [AcmeDemoBundle]]

    sonata.admin.player:
        class: SlashStudio\AppBundle\Admin\PlayerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Players" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Player
            - ~

    sonata.admin.nationality:
        class: SlashStudio\AppBundle\Admin\NationalityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Nationalities" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Nationality
            - ~

    sonata.admin.partnership:
        class: SlashStudio\AppBundle\Admin\PartnershipAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Partnership" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Partnership
            - ~

    sonata.admin.simple_page:
        class: SlashStudio\AppBundle\Admin\SimplePageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Team pages" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\SimplePage
            - ~

    sonata.admin.slide:
        class: SlashStudio\AppBundle\Admin\SlideAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Slides" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Slide
            - ~

    sonata.admin.team:
        class: SlashStudio\AppBundle\Admin\TeamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Team information" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Team
            - ~

    sonata.admin.achievement:
        class: SlashStudio\AppBundle\Admin\AchievementAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Achievements" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Achievement
            - ~

    sonata.admin.post:
        class: SlashStudio\AppBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Posts" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Post
            - ~

    sonata.admin.product:
        class: SlashStudio\AppBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Products" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\Product
            - ~

    sonata.admin.mediapost:
        class: SlashStudio\AppBundle\Admin\MediaPostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "MediaPosts" }
        arguments:
            - ~
            - SlashStudio\AppBundle\Entity\MediaPost
            - ~

