slash_app_mainpage:
    path:       /{_locale}
    defaults: {_controller: SlashStudioAppBundle:App:index, _locale: ru}

slash_app_products:
    resource: "@SlashStudioAppBundle/Resources/config/products_routing.yml"

slash_app_team:
    prefix: /team
    resource: "@SlashStudioAppBundle/Resources/config/team_routing.yml"
