services:
    my_mailer:
        class: SlashStudio\AppBundle\Mailer\Mailer
        arguments: [@mailer, @libphonenumber.phone_number_util, @translator, "%mailer_user%"]

    slash_studio_app.form.type.team_proposal_membership:
        class: SlashStudio\AppBundle\Form\Type\TeamProposalMembershipType
        tags:
            - { name: form.type, alias: team_proposal_membership }

    sonata.block.service.team:
        class: SlashStudio\AppBundle\Block\TeamBlockService
        arguments: [ "sonata.block.service.team", @templating, @sonata.admin.pool, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }

    sonata.block.service.cheerleader:
        class: SlashStudio\AppBundle\Block\CheerleaderBlock
        arguments: [ "sonata.block.service.cheerleader", @templating, @sonata.admin.pool, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }

    sonata.block.service.simple_pages:
        class: SlashStudio\AppBundle\Block\SimplePagesBlock
        arguments: [ "sonata.block.service.simple_pages", @templating, @sonata.admin.pool, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }

#    slash_studio_app.example:
#        class: SlashStudio\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
