imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }

fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

a2lix_translation_form:
    locale_provider: default
    locales: [en, ru]
    default_locale: ru
    required_locales: [en]
    manager_registry: doctrine
    templating: "A2lixTranslationFormBundle::default.html.twig"

sonata_admin:
    title:      Wild Pandas Admin
    dashboard:
        blocks:
            - { position: left, type: sonata.block.service.team, settings: { amount: 5 } }
            - { position: center, type: sonata.block.service.cheerleader, settings: { amount: 5 } }
            - { position: right, type: sonata.block.service.simple_pages }
            - { position: left, type: sonata.admin.block.admin_list, settings: { groups: [admin.posts] } }
            - { position: center, type: sonata.admin.block.admin_list, settings: { groups: [content] } }
            - { position: right, type: sonata.admin.block.admin_list, settings: { groups: [admin.player_group] } }
        groups:
            cheerleader:
                items:
                    - sonata.admin.cheerleader_team
                    - sonata.admin.cheerleaders
            team:
                items:
                    - sonata.admin.team
                    - sonata.admin.achievement
            pages:
                items:
                    - sonata.admin.simple_page

            admin.posts:
                items:
                    - sonata.admin.post
                    - sonata.admin.mediapost
            admin.player_group:
                items:
                    - sonata.admin.position
                    - sonata.admin.nationality
                    - sonata.admin.player
            content:
                items:
                    - sonata.user.admin.user
#                    - sonata.admin.users
                    - sonata.admin.partnership
                    - sonata.admin.slide
                    - sonata.admin.product

            # sonata_page2:
            #     items:
            #         - sonata.page.admin.myitem2
            #         - sonata.page.admin.myitem3
            # sonata_page3:
            #     items:
            #         - sonata.page.admin.myitem4

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.team: ~
        sonata.block.service.cheerleader: ~
        sonata.block.service.simple_pages: ~


framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'SonataMediaBundle:Form:media_widgets.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sonata_media:
    default_context: default
    db_driver: doctrine_orm
    class:
        media:              Application\Sonata\MediaBundle\Entity\Media
        gallery:            Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media:  Application\Sonata\MediaBundle\Entity\GalleryHasMedia
    contexts:
        default:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70 }
                big:   { width: 500 , quality: 100 }

        sliders:
            providers:
                - sonata.media.provider.image

            formats:
                big:   { width: 500, quality: 100 }

        team:
            providers:
                - sonata.media.provider.image

            formats:
                main:   { width: 600, quality: 100 }

        players:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70 }
                big:   { width: 500 , quality: 100 }

        post:
            providers:
                - sonata.media.provider.image

            formats:
                main: { width: 300 , quality: 100 }

        product:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 150 , quality: 70 }
                big:   { width: 300 , quality: 100 }

        achievements:
            providers:
                - sonata.media.provider.image

            formats:
                logo: { width: 90 , quality: 100 }

        partnership:
            providers:
                - sonata.media.provider.image

            formats:
                logo: { width: 100 , quality: 100 }

        cheerleaders:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70 }
                big:   { width: 500 , quality: 100 }

    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
