imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

sonata_admin:
    title:      Wild Pandas Admin
    dashboard:
        blocks:
            - { position: top, type: sonata.block.service.team }
            - { position: center, type: sonata.admin.block.admin_list }
#         groups:
#             acme.admin.group.content:
#                 label: pidor
#                 items:
#                     - sonata.admin.player

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.team: ~


framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'SonataMediaBundle:Form:media_widgets.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sonata_media:
    default_context: default
    db_driver: doctrine_orm
    class:
        media:              Application\Sonata\MediaBundle\Entity\Media
        gallery:            Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media:  Application\Sonata\MediaBundle\Entity\GalleryHasMedia
    contexts:
        default:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70 }
                big:   { width: 500 , quality: 100 }

        sliders:
            providers:
                - sonata.media.provider.image

            formats:
                big:   { width: 500, quality: 100 }

        team:
            providers:
                - sonata.media.provider.image

            formats:
                main:   { width: 600, quality: 100 }

        players:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70 }
                big:   { width: 500 , quality: 100 }

        post:
            providers:
                - sonata.media.provider.image

            formats:
                main: { width: 300 , quality: 100 }

        product:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 150 , quality: 70 }
                big:   { width: 300 , quality: 100 }

        achievements:
            providers:
                - sonata.media.provider.image

            formats:
                logo: { width: 90 , quality: 100 }

        partnership:
            providers:
                - sonata.media.provider.image

            formats:
                logo: { width: 100 , quality: 100 }

        cheerleaders:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70 }
                big:   { width: 500 , quality: 100 }

    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
