# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    sonata.user.admin.user.class: SlashStudio\AppBundle\Admin\UserAdmin
    sonata.seo.twig.extension.class: SlashStudio\AppBundle\Twig\Extensions\SeoExtension
#    parameter_name: value


services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    my_model_manager:
        class: SlashStudio\AppBundle\Admin\ModelManager
        arguments: [@doctrine]

    my_seo:
        class:        SlashStudio\AppBundle\Seo\Seo
        arguments:  [ @sonata.seo.page.default ]

    app.menu_builder:
        class: SlashStudio\AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    app.main_menu:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main }
