sonata_media:
    default_context: default
    db_driver: doctrine_orm
    class:
        media:              Application\Sonata\MediaBundle\Entity\Media
        gallery:            Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media:  Application\Sonata\MediaBundle\Entity\GalleryHasMedia

    contexts:
        default:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70 }
                big:   { width: 740 , quality: 100 }

        sliders:
            providers:
                - sonata.media.provider.image

            formats:
                big:   { width: 810, quality: 100 }

        team:
            providers:
                - sonata.media.provider.image

            formats:
                main:      { width: 370, quality: 100 }
                cl_main:   { width: 840, quality: 100 }

        players:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 80 , quality: 70 }
                big:   { width: 500 , quality: 100 }

        post:
            providers:
                - sonata.media.provider.image

            formats:
                main:  { width: 270 , quality: 100 }
                big:   { width: 770 , quality: 100 }
                small: { width: 133 , quality: 100 }

        product:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 238 , quality: 100 }
                big:   { width: 600 , quality: 100 }

        achievements:
            providers:
                - sonata.media.provider.image

            formats:
                logo: { width: 60 , quality: 100 }

        partnership:
            providers:
                - sonata.media.provider.image

            formats:
                logo: { height: 60 , quality: 100 }

        cheerleaders:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 80 , quality: 100 }
                medium:   { width: 250 , quality: 100 }

        photo:
            providers:
                - sonata.media.provider.image

            formats:
                medium: { width: 350 , quality: 80 }
                big: { width: 800 , quality: 100 }

        team_video:
            providers:
                - sonata.media.provider.vimeo
                - sonata.media.provider.youtube

            formats:
                medium: { width: 360 , quality: 100 }
                big: { width: 370 , quality: 100 }

        team_photo:
            providers:
                - sonata.media.provider.image

            formats:
                main:   { width: 600, quality: 100 }
                big:    { width: 700, quality: 100 }
                medium: { width: 370, quality: 100 }

        cheerleader_team_video:
            providers:
                - sonata.media.provider.vimeo
                - sonata.media.provider.youtube

            formats:
                medium: { width: 400 , quality: 80 }
                big: { width: 800 , quality: 100 }

    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true
