a2lix_translation_form:
    locales:            [en, ru]
    locale_provider:    default
    default_locale:     ru
    required_locales:   [en, ru]
    manager_registry:   doctrine
    templating:         "A2lixTranslationFormBundle::default.html.twig"
