<?php

namespace SlashStudio\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getProductInfo($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p, m, i, t FROM SlashStudioAppBundle:Product p
                  LEFT JOIN p.meta m LEFT JOIN p.image i LEFT JOIN p.translations t
                    WHERE p.id = :id '
            )
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }

    public function getProductsQB()
    {
        return $this->getEntityManager()
                   ->createQueryBuilder()
                   ->select(['p', 'i', 't'])
                   ->from('SlashStudioAppBundle:Product', 'p')
                   ->leftJoin('p.image', 'i')
                   ->leftJoin('p.translations', 't');
    }

    public function getProductsForMainPage()
    {
        return $this->getProductsQB()->where('p.showOnTheMain = true')->getQuery()->getResult();
    }
}
