<?php

namespace SlashStudio\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getProductInfo($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p, m, i FROM SlashStudioAppBundle:Product p LEFT JOIN p.meta m LEFT JOIN p.image i WHERE p.id = :id ')
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }

    public function getProducts($isMainPage = false)
    {
        $qb = $this->getEntityManager()
                   ->createQueryBuilder()
                   ->select(['p', 'i'])
                   ->from('SlashStudioAppBundle:Product', 'p')
                   ->leftJoin('p.image', 'i')
                   ->orderBy('p.name', 'ASC');
        if ($isMainPage) {
            $qb->where('p.showOnTheMain = true');
        }

        return $qb->getQuery()->getResult();
    }
}
