<?php

namespace SlashStudio\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getProductInfo($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p, m FROM SlashStudioAppBundle:Product p LEFT JOIN p.meta m WHERE p.id = :id ')
            ->setParameter('id', $id)
            ->getOneOrNullResult(Query::HYDRATE_ARRAY);
    }

    public function getProductsForMainPage()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM SlashStudioAppBundle:Product p WHERE p.showOnTheMain = true ORDER BY p.name ASC')
            ->getArrayResult();
    }
}
